create table "public"."office" (
    "id" bigint generated by default as identity not null,
    "office_name" text not null
);


alter table "public"."office" enable row level security;

CREATE UNIQUE INDEX office_pkey ON public.office USING btree (id);

alter table "public"."office" add constraint "office_pkey" PRIMARY KEY using index "office_pkey";

grant delete on table "public"."office" to "anon";

grant insert on table "public"."office" to "anon";

grant references on table "public"."office" to "anon";

grant select on table "public"."office" to "anon";

grant trigger on table "public"."office" to "anon";

grant truncate on table "public"."office" to "anon";

grant update on table "public"."office" to "anon";

grant delete on table "public"."office" to "authenticated";

grant insert on table "public"."office" to "authenticated";

grant references on table "public"."office" to "authenticated";

grant select on table "public"."office" to "authenticated";

grant trigger on table "public"."office" to "authenticated";

grant truncate on table "public"."office" to "authenticated";

grant update on table "public"."office" to "authenticated";

grant delete on table "public"."office" to "service_role";

grant insert on table "public"."office" to "service_role";

grant references on table "public"."office" to "service_role";

grant select on table "public"."office" to "service_role";

grant trigger on table "public"."office" to "service_role";

grant truncate on table "public"."office" to "service_role";

grant update on table "public"."office" to "service_role";


